### ISSUE TITLE
Improve pipeline creation UI

### ISSUE THREAD

**Issue by AndreaCatania** [GodotECS/godex#39]
Bound with https://github.com/GodotECS/godex/issues/38

**issue**
When a new pipeline is added, it's created without any `System`s in it, so the developer has to populate it before even be able to use it.

**proposal**
To improve it, a solution would be pre populate the pipeline, so the developer can immediately use it.

In addition to this the `WorldECS` could come with the pipelines already setup: this would reduce beginners entry cost, and improve usability.

**Tracker**
- [x] Add WorldECS warning to better guide the user. #191
- [x] Make the WorldECS ready to use by default. #191
- [x] Add editor to show the pipeline composed by the `PipelineBuilder`.  #186
- [x] The pipeline view must show the pipeline dispatcher #194
- [x] Show the `PipelineBuilder` warning messages on the WorldECS node #192
- [x] Show the `PipelineBuilder` warning messages on the editor world ecs #192

**Comment by AndreaCatania** [comment]
Please, couple this proposal with this: https://github.com/GodotECS/godex/issues/38

**Comment by AndreaCatania** [comment]
@Adevald proposed the following UI design, to improve the ecs UI:
![unknown](https://user-images.githubusercontent.com/8342599/118775847-a566b700-b887-11eb-94d2-7c7c28099abf.png)

Left side we have the pipeline composition, where we can add `SystemBundle`s and `System`s. Right side we have the godex compiled pipeline, with the various created stages.
